# .graphclientrc.yml
sources:
  - name: safire
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/99901/safire/version/latest


documents:
  - ./queries/active-insurance.graphql
  - ./queries/inactive-insurance.graphql